### ISSUE TITLE
TYPO3 8

### ISSUE THREAD

**Issue by Scopestyle** [tollwerk/TYPO3-ext-tw_googleanalytics#10]
Hi @jkphl

It seems that the plugin is not (yet) compatible with TYPO3 8. Are there plans to update?

**Comment by jkphl** [comment]
@Scopestyle Actually, we're already using the extension with TYPO3 8.7 (without any issues). Did you use the latest release? What exactly doesn't work for you?

**Comment by Scopestyle** [comment]
Sorry for the extremely late reply. This is the code that gets rendered in the client:


<script type='text/javascript'>
--
  | (function (d, t) {
  | var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
  | bh.type = 'text/javascript';
  | bh.src = '//www.bugherd.com/sidebarv2.js?apikey=ir4t1xdc29rvsciob5e19w';
  | s.parentNode.insertBefore(bh, s);
  | })(document, 'script');
  | </script>
  | <script type="text/javascript">
  |  
  | 0
  | {$analyticsID}
  | auto
  |  
  | 1
  | 1
  | 1
  | 1
  | 0,'',[]
  | 2,'Email',[]
  | 2,'Download','{filename}',{"\/":["doc","docx","pdf","xls","ppt","zip","gz","bz2","rar","txt","vsd","vxd","js","css","exe","wma","mov","avi","wmv","mp3","mp4"]}
  | []
  | /
  | analytics.js
  |  
  | </script>

**Comment by Scopestyle** [comment]
You know what, this happened because I grabbed the plugin from the repository, assuming it was the same, I just downloaded it from here and it works just fine. Sorry!

**Comment by jkphl** [comment]
Yeah, sorry. I should have mentioned that I stopped publishing to the TER a while back ...

**Comment by Scopestyle** [comment]
I'm honestly interested in your reasoning for that. I blindly assumed grabbing from TER just gives me latest available version of anything I want to use. Is it a pain to update to TER as an extension developer?

I did notice that there are other plugins (like VHS) that release to TER autmatically from Github. Might be worth looking into ...

**Comment by jkphl** [comment]
@Scopestyle Yes, publishing to TER at least *was* a real pain at some point (we needed to keep a TYPO3 4.x or 6.x installation alive to do just that, don't really remember; or we would have to use some other voodoo stuff). As we're only doing composer installs nowadays, installing via Packagist is so much more convenient. And yes, Claus did some magic to automatically release to the TER, but I didn't have time to dig into that so far ... Maybe I'll do that one day. ;)
