### ISSUE TITLE
Google user id tracking

### ISSUE THREAD

**Issue by stwsimon** [tollwerk/TYPO3-ext-tw_googleanalytics#4]
It would be excellent if Google's user id tracking could be added to this great extension, as in:  https://developers.google.com/__analytics/devguides/__collection/analyticsjs/user-id

**Comment by jkphl** [comment]
@jkphl Note to self: See https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#user_id By default, the ID of the currently logged in frontend user could be used as ID for GA, but alternative ways of determining the ID should be possible. TypoScript based solution?
