### ISSUE TITLE
Tracking Videos

### ISSUE THREAD

**Issue by Scopestyle** [tollwerk/TYPO3-ext-tw_googleanalytics#6]
Hi @jkphl 

I am looking for a way to track videos (play and duration) is this something the plugin could handle? 

We are using [video.js](http://www.videojs.com/) to embed the videos, and I have tried using [videojs-ga](https://github.com/mickey/videojs-ga) as a way to track clicks and duration. But this didn't work because the .ga tag in js does not exist. I guess that makes sense because the tw plugin does not answer to that. 

Would you have any suggestions on how we could achieve this?

Looking forward to your reply,

Erik

**Comment by jkphl** [comment]
Hi @Scopestyle,

that should totally be possible by [tracking events](https://github.com/tollwerk/TYPO3-ext-tw_googleanalytics/blob/master/Resources/Public/Js/tw_googleanalytics_universal.js#L630). Simply call `tw_gat.trackEvent(category, action, label, value)` to send an event signal to GA and you should be able to see it there. For a detailed explanation of tracking events please have a look at the [GA developer docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/events).

Hope this helps, cheers,
Joschi

**Comment by jkphl** [comment]
@Scopestyle Did you ever have the chance to test my suggestion? Did it work? As you never responded I will close this issue for now, but please feel free to get in touch with me in case of further questions.
