### ISSUE TITLE
In-Page-Analyse

### ISSUE THREAD

**Issue by ninitsch** [tollwerk/TYPO3-ext-tw_googleanalytics#7]
Dear @jkphl.

This issue is related to our email contact from 15.07.2015.

To activate the inpage-analysis from google analytics it is necessary, to implemet code into the javascript. It would be very nice, if this feature could be included in near future. See this link:
https://support.google.com/analytics/answer/2558867?hl=de&utm_id=ad

Thank you.
Nico

**Comment by jkphl** [comment]
@ninitsch Well, in the end it took me **MUCH** longer than expected, but I **FINALLY** found some time to step through the various issues now. I added support for enhanced link attribution, although the original reference to the Google help pages don't seem valid anymore. I found some information [here](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution).

The enhanced link attribution feature is not documented yet, but I'd ask you to try it out nevertheless. Please install the latest extension release (from Github!) and you'll find some new options in the TYPO3 constant editor. The parameters are the ones you'll also find in [Google's documentation](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution).

Please let me know if this works for you!
