### ISSUE TITLE
Increase dependancy in the Extension Manager

### ISSUE THREAD

**Issue by Scopestyle** [tollwerk/TYPO3-ext-tw_googleanalytics#8]
Hi @jkphl, It might be a good idea to increase the dependancy check. Right now when downloading the plugin you get the following message:

> Your TYPO3 version is higher than this extension requires. It requires TYPO3 versions 6.0.0 - 7.0.99

As we are currently way beyond 7.0.x this might discourage users to try this awesome plugin :smile:

**Comment by jkphl** [comment]
@Scopestyle Good point, thanks for the heads up. Will try to find some time to do this!
